# Generated by Django 2.1.5 on 2019-02-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('cart_items', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.Product')),
                ('disliked_items', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disliked_items', to='products.Product')),
                ('liked_items', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to='products.Product')),
            ],
            options={
                'db_table': 'Swipers',
            },
        ),
    ]
