# Generated by Django 2.1.5 on 2019-02-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_id'),
        ('swiper', '0002_swiper_next_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiper',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='swiper',
            name='cart_items',
            field=models.ManyToManyField(default=1, related_name='cart_items', to='products.Product'),
        ),
        migrations.RemoveField(
            model_name='swiper',
            name='disliked_items',
        ),
        migrations.AddField(
            model_name='swiper',
            name='disliked_items',
            field=models.ManyToManyField(default=1, related_name='disliked_items', to='products.Product'),
        ),
        migrations.RemoveField(
            model_name='swiper',
            name='liked_items',
        ),
        migrations.AddField(
            model_name='swiper',
            name='liked_items',
            field=models.ManyToManyField(default=1, related_name='liked_items', to='products.Product'),
        ),
    ]
